# Setup
title:               o24 notes
tagline:             'A Jekyll theme'
description:         'Notes on pulling portfolio projects into cards and onto Jekyll. Made by <a href="os.koe.pt" target="_blank">os</a>. 2024.'
url:                 https://oscott.github.io/lanyon
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Oliver Scott
  url:               https://os.koe.pt
  email:             os@koept.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
